name: Update Model Catalog

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC every day
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Fetch and update catalog
        run: python scripts/update_catalog.py
        env:
          REGOLO_API_KEY: ${{ secrets.REGOLO_API_KEY }}
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add catalog-v1.csv
          git diff --staged --quiet || git commit -m "Update catalog-v1.csv [automated]"
          git push


